permalink: /:year/:month/:day/:title
highlighter: pygments
markdown: redcarpet

exclude: [
  TODO,
  README.md,
  develop,
  build,
  Gemfile,
  Gemfile.lock
]

redcarpet:
  extensions: ["smart"]

# Custom variables:
disqus: "william-cheung-etw"

category_names:
  "algorithms": "Algorthms"
  "android": "Android"
  "c": "C"
  "code": "Coding"
  "computer-networks": "Computer Networks"
  "cpp": "C++"
  "distributed-systems": "Distributed Systems"
  "go": "Go"
  "language": "Programming Languages"
  "oop": "OOP"
  "os": "O/S Design"
  "python": "Python"
  "unix": "Unix/Linux"
